.PHONY: all clean run pack build-pre build-post

all: build-pre run build-post	
	
build-post: 

run: 
	@cd verify && ./run_all.sh ../main.js

pack:
	zip -r alfyasm.zip alf_computer32.cpu verify/ CPUSim4.0.9/ Makefile.checker\
		README.md 

clean:
	rm -rf verify/output/
